gp:
  population_size: 500              #Increased population for better exploration
  generations: 50                   #More generations to allow convergence
  mutation_rate: 0.3                #Higher mutation for diversity
  crossover_rate: 0.7
  max_depth: 6                      #Increased max depth
  
datasets:
  regression: [diabetes, boston, california_housing]
  classification: [iris, wine, breast_cancer, digits]
  
visualization:
  show_plots: true
  save_plots: true
  plot_dir: "../outputs/"
